name: Terraform Security Check
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change to infrastructure directory
        run: cd infrastructure

      - name: Install tfsec
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?_Linux_x86_64\.tar.gz")" --output tfsec.tar.gz
          tar -xzf tfsec.tar.gz
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec
        run: tfsec
